services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    restart : always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./dump:/dump:ro
volumes:
  mongo_data:
